# General Settings
title = "Dudes With Hands, Your Moving A-TEAM! | Call 617-519-1141 today!"
baseURL = "https://www.dudeswithhands.com/" 
languageCode = "en-us"
theme = "mytheme"
resourceDir = "resources"
paginate = 10
summaryLength = 30 
DefaultContentLanguage = "en"

[backend]
name = "git-gateway"
branch = "main"


# Menu Settings
[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "#about-section"
  weight = 1


[[menu.main]]
  identifier = "pricing"
  name = "Pricing"
  url = "#pricing-section"
  weight = 4
[[menu.main]]
  identifier = "blog"
  name = "Moving FAQ"
  url = "#blog-section"
  weight = 5
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "#contact-section"
  weight = 6


# Main Settings
[params]
defaultSkin = "dark"
dateFormat = "January 2, 2006"
authorName = "BMickman"
googleAnalytics = "G-TR8NRCFF6T"
  logo = "/images/dudeslogo.png" 
  description = "NYC's Favorite Affordable Moving A-TEAM! Call 617-519-1141 Today!"


# Preloader Settings
[params.preloader]
logo = "images/dudeslogo.png"

# Header Settings
[params.header]
logo = "images/dudeslogo.png"

# Footer Settings
[params.footer]
copyright = "© 2024 Dudes With Hands. All Rights Reserved"
developer = "Notorious Octopus"

# Social Settings

[[params.social]]
title = "Google Maps"
icon = "fab fa-google"
url = "https://g.page/dudeswithhands/"
weight = 1
[[params.social]]
title = "Facebook"
icon = "fab fa-facebook"
url = "https://www.facebook.com/dudeswithhands/"
weight = 2

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "UI UX Design"
slug = "ui-ux-design"
[[params.portfolio.filters]]
name = "Photography"
slug = "photography"
[[params.portfolio.filters]]
name = "Development"
slug = "development"
[[params.portfolio.filters]]
name = "Branding"
slug = "branding"

# Sitemap Settings
[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"
